# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RealmDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RealmDemo
pod 'Alamofire', '~> 4.4'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'ReachabilitySwift', '~> 3'
pod 'RealmSwift' 
end
